{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.0.0.aar",
          "url": "material3-1.0.0.aar",
          "size": 2884960,
          "sha512": "ec49d226e1d53d26eb3aa9fe85465c63d1c5c555b5f6d8b6e7b94397b381781d5cd423a9d971cf2a20655ecd4def3e17d6d30c5cb32172b5b802b4e8ec322724",
          "sha256": "2d4235830df205e352e04def892f4798b1e9fba265ec43b7ce3818a21440746a",
          "sha1": "ad3c74e7b9aef09d5139a4751074fbf46429a5ff",
          "md5": "c064e761ac9a652ed8058a9f04f688e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.0.0.aar",
          "url": "material3-1.0.0.aar",
          "size": 2884960,
          "sha512": "ec49d226e1d53d26eb3aa9fe85465c63d1c5c555b5f6d8b6e7b94397b381781d5cd423a9d971cf2a20655ecd4def3e17d6d30c5cb32172b5b802b4e8ec322724",
          "sha256": "2d4235830df205e352e04def892f4798b1e9fba265ec43b7ce3818a21440746a",
          "sha1": "ad3c74e7b9aef09d5139a4751074fbf46429a5ff",
          "md5": "c064e761ac9a652ed8058a9f04f688e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-1.0.0-sources.jar",
          "url": "material3-1.0.0-sources.jar",
          "size": 267794,
          "sha512": "2c41a30d5e45009bdf0608ba92a8ce60fb887895d5520db9b891468b8280f4760f6e946cfa7e3a799ad2353e33d2e739ce519656516a4a2d1e57c0912ff6223f",
          "sha256": "a578f3e7f3dcfb7e12d7dada1095f3afa3d0747c0d8dfbae52d68782463b5d3f",
          "sha1": "5fbf543f63fc69bb6e463069547f306491daef2f",
          "md5": "8b831cc3cd67d409cdf55e7a11068bb7"
        }
      ]
    }
  ]
}