{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-samples",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.4.0.aar",
          "url": "runtime-1.4.0.aar",
          "size": 2127890,
          "sha512": "38a75815416e007486de36b4941b3589a0fc5c75eea550eb7bc62677fc993034ef1b682e0f78e6d9681ff556560220539f1d0a9c378664a6f123130193f1c42a",
          "sha256": "0b6e672a16ba336961d72676281e49955a92fda071725adefaecaaa9427d567e",
          "sha1": "5709ea50feb42f161d3f00b8b2438a86440e9dc2",
          "md5": "3602562f039aab5bd32bdc10acd82fc4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-samples",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.4.0.aar",
          "url": "runtime-1.4.0.aar",
          "size": 2127890,
          "sha512": "38a75815416e007486de36b4941b3589a0fc5c75eea550eb7bc62677fc993034ef1b682e0f78e6d9681ff556560220539f1d0a9c378664a6f123130193f1c42a",
          "sha256": "0b6e672a16ba336961d72676281e49955a92fda071725adefaecaaa9427d567e",
          "sha1": "5709ea50feb42f161d3f00b8b2438a86440e9dc2",
          "md5": "3602562f039aab5bd32bdc10acd82fc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-samples",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-samples",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.4.0-sources.jar",
          "url": "runtime-1.4.0-sources.jar",
          "size": 310872,
          "sha512": "00a176ab2effb9b5880540b8dec7023caf3a53fcc10009eae538d6577436d7f1ee724e3947ff8a890ca04cb5e165d03616d48f5185f5fa7ee754ac9209c3494a",
          "sha256": "994b6837c908348c87bc59e3235b31adca6388b27e78c70b11f7f0d55f6bed22",
          "sha1": "b671770047fe34c1e91c0b8dcbf835e1b920a276",
          "md5": "41ae693a2ac45b0dbc18e0f9206abb05"
        }
      ]
    }
  ]
}