{
  "formatVersion": "1.1",
  "component": {
    "group": "org.firstinspires.ftc",
    "module": "RobotCore",
    "version": "10.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "RobotCore-10.1.0.aar",
          "url": "RobotCore-10.1.0.aar",
          "size": 2372230,
          "sha512": "d16e0a029197f9af641b1c4e68e053a7defdbbabd8ee2bc56186f4110aa67973f60df8d743be34ed36139e4897f3a4cc4f029ff64e3b28a16774e87fd2208752",
          "sha256": "486ea7e414152ae803add6f2ed0a8e930c9a5a817b7fc0dea27a851b82295218",
          "sha1": "b2aae2afbf2ab1fa7157ec009af4f9d1d7391ca0",
          "md5": "5185decc92319de011406e46e796e54e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "RobotCore-10.1.0.aar",
          "url": "RobotCore-10.1.0.aar",
          "size": 2372230,
          "sha512": "d16e0a029197f9af641b1c4e68e053a7defdbbabd8ee2bc56186f4110aa67973f60df8d743be34ed36139e4897f3a4cc4f029ff64e3b28a16774e87fd2208752",
          "sha256": "486ea7e414152ae803add6f2ed0a8e930c9a5a817b7fc0dea27a851b82295218",
          "sha1": "b2aae2afbf2ab1fa7157ec009af4f9d1d7391ca0",
          "md5": "5185decc92319de011406e46e796e54e"
        }
      ]
    }
  ]
}
