{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-daemon",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-1.4.3.jar",
          "url": "compiler-1.4.3.jar",
          "size": 990401,
          "sha512": "af5e94434c66ecf0ad2117140d0dd3ac4b3a0f13f3c22fde6cb687e66a15b93c9c230b3411db39046050f7c0a3bb6c27642678ad4381283cf313de49bb3920b9",
          "sha256": "43fcad86835221accdc8c4043fa52d2dfcc8d66442498d298c6404376d18d17c",
          "sha1": "3d5ff820c24eb2c70ee29237f5b60403dd2c39fd",
          "md5": "e852ca63e68d86f543b446eb575a1ba9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-daemon",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-1.4.3.jar",
          "url": "compiler-1.4.3.jar",
          "size": 990401,
          "sha512": "af5e94434c66ecf0ad2117140d0dd3ac4b3a0f13f3c22fde6cb687e66a15b93c9c230b3411db39046050f7c0a3bb6c27642678ad4381283cf313de49bb3920b9",
          "sha256": "43fcad86835221accdc8c4043fa52d2dfcc8d66442498d298c6404376d18d17c",
          "sha1": "3d5ff820c24eb2c70ee29237f5b60403dd2c39fd",
          "md5": "e852ca63e68d86f543b446eb575a1ba9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-daemon",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-1.4.3-sources.jar",
          "url": "compiler-1.4.3-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}